### PR TITLE
Fix encoding of 9-digits MSIN when MNC is 3 digits

### PR DESCRIPTION
**Pull request by linouxis9**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
Fix https://github.com/HewlettPackard/PacketRusher/issues/98

- [X] All new and existing tests passed.

- [X] I have read the **CONTRIBUTING** document.
- [X] Each of my commits messages include `Signed-off-by: Author Name <authoremail@example.com>` to accept the DCO.

### CODE REVIEW

**Comment by linouxis9** [comment]
Hi @rjaksa,

Could you test the fix?

Thanks a lot!

Cheers,
Valentin

**Comment by rjaksa** [comment]
In tools.go...

The 9-digit MSINs look correct for both ueCfg and simConfig now (as shown when adding the "Debug 1" and "Debug 2" lines mentioned in the original issue description). 

But simConfig.Gnbs[gnbIdGen(0)] is still NULL (i.e. output of "Debug 3" in the original bug report is still <nil>), so PacketRusher crashes in tools.go due to a nil pointer dereference.

**Comment by linouxis9** [comment]
@rjaksa
I'm not hitting the issue where the gnbs array is empty when using a 3-digits MNC / 9-digits msin, everything seems to work on my side.
I'll try to reproduce again.
Could you share the log of the crash?
Thanks a lot!

**Comment by linouxis9** [comment]
Or maybe you are referring to this crash? https://github.com/HewlettPackard/PacketRusher/pull/104

**Pull request merged**
