### PR TITLE
Use Registration instead of Service Request to switch from CM-IDLE to CM-CONNECT when 5G-GUTI was not assigned by AMF

### LINKED ISSUE #79: [BUG] Xn and Ng Handover command
Hi,

I attach the bug I had while executing: sudo ./packetrusher multi-ue -n 1 -xnh 3000 -idl 13000 -ngh 23000 --tunnel --dedicatedGnb

In the following picture you can observe the free5gc on the left and, the output of the PacketRusher.

image

I attach the pcap file.

[pcap.zip](https://github.com/HewlettPackard/PacketRusher/files/14277724/pcap.zip)

Thank you for the support.

Ignacio

### PR DESCRIPTION
**Pull request by linouxis9**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
Fix #79
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have read the **CONTRIBUTING** document.
- [X] Each of my commits messages include `Signed-off-by: Author Name <authoremail@example.com>` to accept the DCO.

### CODE REVIEW

**Comment by linouxis9** [comment]
Hi @IgnacioCTO,
Can you check that this PR fixes the issue you had in #79?
Thanks a lot!
Valentin

**Review by Raguideau — APPROVED** [review]

**Comment by IgnacioCTO** [comment]
hi @linouxis9! Sorry for my late response.

I think that i am getting the same error... In principle, I pulled your commit that correspond to the fix.

I attach the dump file

[Dump.zip](https://github.com/HewlettPackard/PacketRusher/files/14388592/Dump.zip)

**Comment by linouxis9** [comment]
Hi @IgnacioCTO,

According to this comment https://github.com/omec-project/gnbsim/issues/126#issuecomment-1921643817 , Free5GC might not support ServiceRequest. I'll take a look and test with Free5GC. For now, my test have been with Open5GS.

Thanks a lot,
Valentin

**Comment by IgnacioCTO** [comment]
Hello @linouxis9,

Do you recommend me to work with Open5GS then, is it more complete?

On the other hand, I am trying to implement the functionality of the N2 handover on UERANSIM (5G Ran implementation packet) + free5gc, but I am struggling to handle the END MARKER message on the gNB, could you give me any indication on this topic if you are so kind.

Thank you for your time.

Ignacio

**Comment by linouxis9** [comment]
Hi @IgnacioCTO,
I advise you to use PacketRusher first and foremost;-)
Jokes aside, both have different strengths. I advise you to test your implementation with both of them since using a different 5G Core with a slightly different behavior usually allows you to either find bugs in your simulator or in the 5G Core.
What is the issue you are having with End Marker? This GTP-U message only means that no more GTP-U data is going to be sent on this tunnel by the sending party. You just have to close the GTP-U tunnel on reception of this message.

Cheers,
Valentin

**Comment by IgnacioCTO** [comment]
Good morning @linouxis9,

I would be pleased to use PacketRusher hahah but since I can't split the gNB and the UE I might need to implement the Xn handover myself into UERANSIM.

Regarding the END MARKER, I am honestly a bit lost, it is the first time I work with the 5G protocols. So far I found an incomplete implementation that is able to send the PathSwitchRequest to the core but the UE doesn't really switch the tunnel to the new gnb. I don't know if you have any good reference that could help me to learn about this topic at implementation level, as you have developed the PacketRush library.

Thanks a lot, cheers.

Ignacio

**Comment by linouxis9** [comment]
Hi @IgnacioCTO,

Look at the PathSwitchRequest in this [pcap](https://github.com/HewlettPackard/PacketRusher/files/13789410/PacketRusher-Successive.NGAP.Handover.and.then.Xn.Handover.zip) (you can ignore the Handover messages, it's related to NGAP Handover, in your case, you only have PathSwitchRequestTransfer[Acknowledge] messages).

Basically for Uplink (gNb2 -> UPF), you re-use the tunnel information that was sent to gNb1, and for Downlink (UPF -> gNb2), you send the tunnel information to the AMF inside a PathSwitchRequestTransfer.
Once you receive a PathSwitchRequestTransferAcknowledge from the AMF, you should be able to send traffic from gNb2 to the UPF using the tunnel info passed down from gNb1, and receive data from the information you sent inside PathSwitchRequestTransfer.

There is nothing special to handle about the End Marker, except you should not send any more traffic from gNb1 when you receive this message.

Cheers,
Valentin

**Pull request merged**
